"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
linemode = "mtime"

[preview]
tab_size = 4
max_width = 1200
max_height = 1800

[plugin]
prepend_previewers = [{ name = "*.ipynb", run = "nbpreview" }]
